## Упражнения по библиотеке Numpy

In [1]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [2]:
# your code
arr = np.random.randint(10, size=100)
arr = np.where((arr >=3) & (arr <=8), -arr, arr)
arr

array([-3,  2,  1,  9, -5, -3, -7, -3,  2,  1, -7, -6, -7, -4, -7, -8,  0,
       -6, -3, -4, -7,  9, -5, -3,  2, -5, -4,  1,  0,  0,  0,  0, -7, -3,
        1, -4, -7,  2, -6,  0,  2, -8, -5, -8,  0, -8, -6,  9, -4,  2, -3,
       -6,  1, -3, -6,  1, -5, -5, -6, -5, -6,  1, -7, -8, -8, -5, -8, -7,
        9, -7,  0, -5, -7, -7,  9,  0, -6, -8,  0,  2, -7, -6,  2,  9, -5,
       -3, -4, -7,  9, -6, -6,  2, -5, -7, -3,  0, -7, -4,  9,  1])

**2.** Заменить максимальный элемент случайного массива на 0

In [3]:
arr = np.random.randint(10, size=100)
arr = np.where(arr == arr.max(), 0, arr)
arr

array([0, 0, 7, 8, 2, 0, 1, 5, 6, 0, 3, 6, 3, 5, 4, 6, 0, 6, 5, 2, 5, 8,
       1, 1, 8, 0, 6, 8, 1, 1, 8, 0, 0, 5, 4, 1, 4, 6, 8, 3, 2, 0, 6, 0,
       0, 0, 7, 4, 2, 3, 5, 8, 3, 1, 7, 1, 2, 0, 8, 3, 7, 4, 0, 2, 6, 6,
       0, 0, 0, 7, 0, 7, 7, 8, 4, 3, 7, 0, 1, 0, 8, 4, 8, 5, 6, 4, 8, 1,
       5, 1, 2, 0, 2, 4, 7, 5, 6, 6, 0, 5])

**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [4]:
def product(arr1, arr2):
    result = np.zeros((arr1.shape[0] * arr2.shape[0], arr1.shape[1] * arr2.shape[1]))
    return result

arr1 = np.random.randint(5, size=(3, 3))
arr2 = np.random.randint(5, size=(2, 2))
product(arr1, arr2)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [7]:
arr1 = np.random.randint(0,5,(8,3))
arr2 = np.random.randint(0,5,(2,2))

multiple_compare = (arr1[..., np.newaxis, np.newaxis] == arr2)
rows = (multiple_compare.sum(axis=(1,2,3)) >= arr2.shape[1]).nonzero()[0]
arr1, arr2, rows

(array([[4, 2, 3],
        [1, 2, 4],
        [3, 4, 3],
        [0, 0, 2],
        [4, 2, 2],
        [3, 2, 1],
        [3, 0, 3],
        [0, 1, 1]]),
 array([[0, 4],
        [3, 4]]),
 array([0, 1, 2, 3, 4, 6]))

**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [8]:
arr = np.random.randint(3, size=(10, 3))
idx = np.where((arr[:, :-1] == arr[:, 1:]).sum(axis=1) == 2)[0]
arr = np.delete(arr, idx, axis=0)
idx, arr

(array([1]),
 array([[0, 2, 2],
        [1, 0, 1],
        [2, 0, 0],
        [0, 2, 0],
        [2, 1, 0],
        [0, 0, 1],
        [1, 0, 2],
        [1, 2, 2],
        [0, 1, 0]]))

**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [9]:
arr = np.random.randint(3, size=(10, 3))
arr = np.unique(arr, axis=0)
arr

array([[0, 0, 0],
       [0, 1, 0],
       [0, 2, 0],
       [0, 2, 2],
       [1, 1, 1],
       [2, 1, 1],
       [2, 1, 2]])

______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [10]:
array = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
min_counts = min(len(array), len(array[0]))
diag = [array[i][i] for i in range(min_counts) if array[i][i] != 0]
res = 1
for el in diag:
    res *= el
print(el)

3


In [11]:
array = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
np.prod(np.where(np.diag(array) == 0, 1, np.diag(array)))

np.int64(3)

* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [12]:
def comparison(x, y):
    return sorted(x) == sorted(y)
            
x = [1, 2, 2, 4]
y = [4, 2, 1, 2]
comparison(x, y)

True

In [13]:
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
x.sort(), y.sort()
np.sum(x == y) == len(x)

np.True_

* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [14]:
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
res = max([x[i+1] for i in range(len(x) - 1) if x[i] == 0])
res

5

In [15]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
res = x[np.where(x[:-1] == 0)[0] + 1].max()
res

np.int64(5)

* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [17]:
def rle(x):
    count = 1
    list_el = []
    list_counts = []
    for i in range(1, len(x)):
        if x[i] == x[i-1]:
            count += 1
        else:
            list_el.append(x[i-1])
            list_counts.append(count)
            count = 1

    list_el.append(x[-1])
    list_counts.append(count)
    return list_el, list_counts
    

x = [2, 2, 3, 4, 3, 3, 2, 5]

rle(x)

([2, 3, 4, 3, 2, 5], [2, 1, 1, 2, 1, 1])

In [18]:
def rle_numpy(array):
    y = np.r_[True, array[1:] != array[:-1]]
    values = array[y]
    idx = np.nonzero(y)[0]
    lengths = np.diff(np.r_[idx, array.size])
    return values, lengths

arr_1 = np.array([2, 2, 3, 4, 3, 3, 2, 5])
arr_2 = np.array([2, 2, 2, 3, 3, 3, 5])
rle_numpy(arr_1)
#rle_numpy(arr_2)

(array([2, 3, 4, 3, 2, 5]), array([2, 1, 1, 2, 1, 1]))

* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [25]:
import math

from scipy.spatial.distance import cdist

In [27]:
%%time
x = np.random.randint(45, size=(100,2))
y = np.random.randint(115, size=(100,2))
dist = np.zeros((100, 100))
for i in range(len(x)):
    for j in range(i + 1, len(y)):
        dist[i, j] = dist[j, i] = math.sqrt((x[i, 0] - y[i, 0]) ** 2 + (x[i, 1] - y[i, 1]) ** 2)
# dist

CPU times: user 26.6 ms, sys: 3.8 ms, total: 30.4 ms
Wall time: 28.1 ms


In [31]:
%%time
x = np.random.randint(45, size=(100,2))
y = np.random.randint(115, size=(100,2))
cdist(x, y, 'euclidean') # быстрее

CPU times: user 1.1 ms, sys: 0 ns, total: 1.1 ms
Wall time: 866 μs


array([[ 27.58622845,  32.01562119,  31.25699922, ...,  93.72299611,
         30.01666204,  72.44998275],
       [ 50.        ,  31.11269837,  27.01851217, ..., 102.00490184,
         51.7880295 ,  95.70788891],
       [ 35.22782991,  33.83784863,  31.57530681, ..., 100.41912169,
         40.01249805,  81.54140053],
       ...,
       [ 48.75448697,  40.45985665,  36.61966685, ..., 110.75197515,
         55.        ,  95.85927185],
       [ 32.69556545,  66.09841148,  64.38167441, ..., 126.75172583,
         53.26349594,  76.00657866],
       [ 44.77722635,  36.61966685,  33.12099032, ..., 106.30145813,
         50.009999  ,  91.54780172]], shape=(100, 100))

_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [32]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [33]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [34]:
average_calories = calorie_stats.mean()
average_calories

np.float64(106.88311688311688)

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [35]:
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [36]:
median_calories = np.median(calorie_stats)
median_calories

np.float64(110.0)

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [37]:
percentile_list = np.arange(0, 100, 5)
np.where(np.percentile(calorie_stats, percentile_list) > 60)[0]
nth_percentile = percentile_list[1]
nth_percentile, np.percentile(calorie_stats, nth_percentile)

(np.int64(5), np.float64(70.0))

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [38]:
more_calories = calorie_stats[calorie_stats > 60].shape[0] / calorie_stats.shape[0]
more_calories

0.961038961038961

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

Для расчёта доверительных интервалов при построении гипотез

In [39]:
calories_std = calorie_stats.std()
calories_std

np.float64(19.35718533390827)

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

# ВЫВОДЫ
Уже на основании этих данных можно сказать, что количество калорий конкурентов значительно превышает количество калорий хлопьев CrunchieMunchies. Данную информацию можно использовать для построения гипотез о предполагаемых продажах, например оценить значимость эффекта